# Settings specific to the LOCAL environment
# Inherits from settings.toml and overrides values.
# Sensitive values are loaded from environment variables (e.g., .env file).

[LOCAL]
# merges with [DEFAULT] from settings.toml

# Postgres (Overrides/Specifics for local)
db_host = "${HYGGE_DB_HOST}" # Default to localhost if env var not set
db_port = "${HYGGE_DB_PORT}"      # Default to 5432 if env var not set
db_database = "${HYGGE_DB_DATABASE}" # Default from local.ini if env var not set
db_user = "${HYGGE_DB_USER}"    # Default from local.ini if env var not set
db_password = "${HYGGE_DB_PASSWORD}"     # No default for password
db_max_connections=20
db_stale_timeout=50
db_options="-csearch_path=public,authentication,support,telemetry,payment,master,transactional,engagement"



# MQTT (Overrides/Specifics for local)
mqtt_id = "${HYGGE_MQTT_ID}" # Default from local.ini
mqtt_broken_url = "${HYGGE_MQTT_BROKEN_URL}" # Default from local.ini
mqtt_application_name = "${HYGGE_MQTT_APPLICATION_NAME=network-topology-local}" # Default from local.ini
mqtt_host = "${HYGGE_MQTT_HOST}"       # Default from local.ini
mqtt_port = "${HYGGE_MQTT_PORT}"          # Default from local.ini
mqtt_username = "${HYGGE_MQTT_USERNAME}" # Default from local.ini
mqtt_password = "${HYGGE_MQTT_PASSWORD}"         # No default for password

# Logging (Overrides/Specifics for local)
logging_level = "DEBUG" # Override default from settings.toml
logging_log_directory = "${HYGGE_LOG_DIRECTORY}" # Default from local.ini

# SMS (Overrides/Specifics for local)

sms_provider_server="https://2factor.in/API/V1"
sms_api_key="30db2df9-5ae4-11eb-8153-0200cd936042"
sms_otp_sms_template_name="Hygge EV"
sms_default_number="1111111111"
sms_topic="hygge/topic/sms/otp"


# Session
session_token_secret = "${HYGGE_SESSION_TOKEN_SECRET}"
session_validity_in_hours=3600
session_validity_in_hours_refresh_token=3600

# Topic - Local might not need this section if it's dev/test specific
# Remove or comment out if not applicable to local
# topic_topics = "..."

# Simulation - Assuming defaults from settings.toml are okay for local
simulacion_initial_battery_soc = 0
simulacion_solar_peak_percentage_for_charging = 40
simulacion_load_peak_percentage_for_discharging = 95
simulacion_charge_battery_efficiency = 100
simulacion_discharge_battery_efficiency = 100
simulacion_default_panel_capacity = 540
simulacion_default_battery_capacity_required = 800
simulacion_battery_dynamic_percentage_allocation = 40
simulacion_battery_base_percentage_allocation = 30

otp_max_otp_verification_attempts=3
otp_max_resend_otp_attempts=3
otp_max_resend_otp_attempt_window_in_min=15
otp_validity_in_secs=180
otp_master_otp_admin = 215543
otp_master_otp_user = 543215
otp_admin_number = 6475295635
otp_user_number = 6475295636

# CORS - Assuming defaults from settings.toml are okay for local
cors_origins = "*"
cors_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_headers = ["Authorization", "Content-Type"]
cors_allow_credentials = true

load_profile_interpolation_strategy = "Linear"
load_profile_max_interval_length = 24
load_profile_min_days = 360
load_profile_time_formats = "%d/%m/%Y %H:%M,%d-%m-%Y %H:%M,%m/%d/%Y %H:%M,%Y-%m-%d %H:%M,%Y/%m/%d %H:%M,%d/%m/%Y,%d-%m-%Y,%m/%d/%Y,%Y-%m-%d,%Y/%m/%d"
