# Base settings for all environments
# Values here can be overridden by environment-specific .toml files (dev, local, etc.)
# or by environment variables.

[DEFAULT]

# Postgres Defaults (Host, Port, DB, User, Pass should be in .env or env-specific files)
postgres_max_connections = 20
postgres_stale_timeout = 50
postgres_options = "-csearch_path=public,authentication,support,telemetry,payment,master,transactional,engagement"

# MQTT Defaults (ID, URL, AppName, Host, Port, User, Pass should be in .env or env-specific files)
# No common defaults identified for MQTT base settings other than potentially port if consistent

# Logging Defaults (Directory should be in .env or env-specific files)
logging_level = "INFO"
logging_system_user_id = "0bfee797-1207-4d36-8ab8-3796acb152d6" # Consider if this should be env-specific

# OTP (Seems consistent across environments)
otp_max_otp_verification_attempts = 15
otp_max_resend_otp_attempts = 15
otp_max_resend_otp_attempt_window_in_min = 30
otp_otp_validity_in_secs = 180
otp_master_otp_admin = 215543
otp_master_otp_user = 543215
otp_admin_number = 6475295635
otp_user_number = 6475295636

# SMS Defaults (Provider Server, API Key should be in .env or env-specific files)
sms_otp_sms_template_name = "Hygge EV"
sms_default_number = "1111111111"
sms_topic = "hygge/topic/sms/otp"

# Session Defaults (Secret should be in .env)
session_validity_in_hours = 3600
session_validity_in_hours_refresh_token = 3600

# CORS (Seems consistent across environments)
cors_origins = "*"
# Dynaconf expects lists for TOML arrays, ensure correct formatting if needed
# cors_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"] # Example if list needed
# cors_headers = ["Authorization", "Content-Type"] # Example if list needed
cors_methods = "GET, POST, PUT, DELETE, OPTIONS" # Keep as string if config parser handles it
cors_headers = "Authorization, Content-Type" # Keep as string if config parser handles it
cors_allow_credentials = true

# Load Profile (Seems consistent across environments)
load_profile_interpolation_strategy = "Linear"
load_profile_max_interval_length = 24
load_profile_min_days = 360
load_profile_time_formats = "%d/%m/%Y %H:%M,%d-%m-%Y %H:%M,%m/%d/%Y %H:%M,%Y-%m-%d %H:%M,%Y/%m/%d %H:%M,%d/%m/%Y,%d-%m-%Y,%m/%d/%Y,%Y-%m-%d,%Y/%m/%d,"

# Simulation (Defaults from int.ini, adjust if needed)
simulation_initial_battery_soc = 0.0
simulation_solar_peak_percentage_for_charging = 40.0
simulation_load_peak_percentage_for_discharging = 95.0
simulation_charge_battery_efficiency = 100.0
simulation_discharge_battery_efficiency = 100.0
simulation_default_panel_capacity = 540.0
simulation_default_battery_capacity_required = 800.0
simulation_battery_dynamic_percentage_allocation = 40.0
simulation_battery_base_percentage_allocation = 30.0

# Topic (Defaults from dev.ini/test.ini, adjust if needed)
# Consider if this section is truly common or should be env-specific
topic_topics = "powermeter/main/meghalaya 2, powermeter/full/meghalaya 2, inverter/meghalaya 2"