# Sensitive values are loaded from environment variables (example.env file).
[TEST]


# Postgres
db_host = "${HYGGE_DB_HOST}" 
db_port = "${HYGGE_DB_PORT}"     
db_database = "${HYGGE_DB_DATABASE}" 
db_user = "${HYGGE_DB_USER}"    
db_password = "${HYGGE_DB_PASSWORD}"     
db_max_connections=20
db_stale_timeout=50
db_options="-csearch_path=public,authentication,support,telemetry,payment,master,transactional,engagement"



# MQTT 
mqtt_id = "network-topology-test"
mqtt_broken_url = "activemq"
mqtt_application_name = "network-topology-test"
mqtt_host = "activemq"
mqtt_port = 1883
mqtt_username = "${HYGGE_MQTT_USERNAME}" 
mqtt_password = "${HYGGE_MQTT_PASSWORD}"       

# Logging 
logging_level = "DEBUG" 
logging_log_directory = "/var/log/application"

# SMS 
sms_provider_server="https://2factor.in/API/V1"
sms_api_key="${HYGGE_SMS_API_KEY}"
sms_otp_sms_template_name="Hygge EV"
sms_default_number="1111111111"
sms_topic="hygge/topic/sms/otp"


# Session
session_token_secret = "${HYGGE_SESSION_TOKEN_SECRET}"
session_validity_in_hours=3600
session_validity_in_hours_refresh_token=3600


# Simulation - Assuming defaults from settings.toml are okay for local
simulation_initial_battery_soc = 0
simulation_solar_peak_percentage_for_charging = 40
simulation_load_peak_percentage_for_discharging = 95
simulation_charge_battery_efficiency = 100
simulation_discharge_battery_efficiency = 100
simulation_default_panel_capacity = 540
simulation_default_battery_capacity_required = 800
simulation_battery_dynamic_percentage_allocation = 40
simulation_battery_base_percentage_allocation = 30

otp_max_otp_verification_attempts=60
otp_max_resend_otp_attempts=60
otp_max_resend_otp_attempt_window_in_min=15
otp_validity_in_secs=180
otp_master_otp_admin = 215543
otp_master_otp_user = 543215
otp_admin_number = 6475295635
otp_user_number = 6475295636

# CORS 
cors_origins = "*"
cors_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
cors_headers = ["Authorization", "Content-Type"]
cors_allow_credentials = true

load_profile_interpolation_strategy = "Linear"
load_profile_max_interval_length = 24
load_profile_min_days = 360
load_profile_time_formats = "%d/%m/%Y %H:%M,%d-%m-%Y %H:%M,%m/%d/%Y %H:%M,%Y-%m-%d %H:%M,%Y/%m/%d %H:%M,%d/%m/%Y,%d-%m-%Y,%m/%d/%Y,%Y-%m-%d,%Y/%m/%d"
